blank_issues_enabled: false
contact_links:
 - name: Getting Help on natural-show
   url: https://github.com/Ctrlable/natural-show/discussions/categories/q-a
   about: Q&A section of the discussion tab
 - name: Share your idea
   url: https://github.com/Ctrlable/natural-show/discussions/categories/ideas
   about: And discuss it with the community
 - name: General discussions about this component
   url: https://github.com/Ctrlable/natural-show/discussions/categories/general
   about: General discussions about this component
 - name: Share your setup with natural-show
   url: https://github.com/Ctrlable/natural-show/discussions/categories/show-and-tell
   about: Or see what other people do with this component
